### ISSUE TITLE
Align TLS options with URLs

### ISSUE THREAD

**Issue by ctron** [ctron/hot#2]
Currently we have the problem that you can specify a TLS based endpoint (e.g. `amqps` vs `amqp`), which would also enable TLS internally. However, if you want to specify a custom TLS certificate, you need to add `-T` and `-P`. Only adding `-P` doesn't work.

I think when using a TLS based endpoint (same for mqtt and http), then `-P` or `--insecure` should be sufficient for configuring TLS.

**Comment by astoycos** [comment]
Ok cool, sounds like a good feature enhancement!  Do you like how we read in the custom certificate via a .crt file, or would you rather have the custom cert be read in via an environment variable or other means?

**Comment by ctron** [comment]
I think reading in the cert with `-P` is fine. Other command line tools follow a similar approach.

Having the tool use a simply and secure approach by default should be the goal IMHO. So by default it uses secure TLS, when TLS enabled via the URL (amqp_s_). Adding `--insecure` then disables the checks. Same for the certificate, by default it uses the system certs, adding `-P` switches to the provided cert file.

**Comment by ctron** [comment]
And taking a second look at the current state, I think adding the `-T` parameter actually wasn't that ideal, sorry for that. I think having the information passed in via the URL was good enough already.

**Comment by astoycos** [comment]
So should I just adapt the code so that the only flags are **--tlsPath**(-P)=certfile (to enable secure TLS) and **--insecure**(-I)=true (To enable Insecure TLS) and then if neither are provided the connection will simply be non-TLS?

**Comment by ctron** [comment]
Sorry, that is not what I meant. The fact that TLS gets enabled comes from the URL provided, e.g. `amqps` (the `s`) would enable TLS in the client, some for http and mqtt. The decision to use TLS would be made by the client. In case it is enabled, it might require additional information (like the cert path, or "insecure mode"). So `-P` and `--insecure` can be provided all the time, and get passed to the client, but I would assume the client only makes use of that, when it detected that TLS has to be used.

**Comment by astoycos** [comment]
Ok great, now we are on the same page!

**Comment by ctron** [comment]
Should be fixed in 0.4.0 already.
